In [1]:
# Import Numpy & PyTorch
import numpy as np
import torch

## Linear Regression Model using PyTorch built-ins

Let's re-implement the same model using some built-in functions and classes from PyTorch.

And now using two different targets: Apples and Oranges

In [2]:
# Imports
import torch.nn as nn

In [3]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

### Dataset and DataLoader

We'll create a `TensorDataset`, which allows access to rows from `inputs` and `targets` as tuples. We'll also create a DataLoader, to split the data into batches while training. It also provides other utilities like shuffling and sampling.

In [5]:
# Import tensor dataset & data loader
from torch.utils.data import TensorDataset, DataLoader

In [6]:
# Define dataset
dataset = TensorDataset(inputs, targets)
dataset[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [7]:

# Define data loader
batch_size = 5
DL = DataLoader(dataset, batch_size, shuffle=True)
next(iter(DL))

[tensor([[ 91.,  88.,  64.],
         [ 69.,  96.,  70.],
         [ 73.,  67.,  43.],
         [102.,  43.,  37.],
         [ 73.,  67.,  43.]]),
 tensor([[ 81., 101.],
         [103., 119.],
         [ 56.,  70.],
         [ 22.,  37.],
         [ 56.,  70.]])]

### nn.Linear
Instead of initializing the weights & biases manually, we can define the model using `nn.Linear`.

In [8]:
# Define model
final_model = nn.Linear(3, 2)
print(final_model.weight, end="\n---------\n")
print(final_model.bias)

Parameter containing:
tensor([[-0.0182,  0.0485, -0.1613],
        [ 0.0964,  0.5227, -0.1537]], requires_grad=True)
---------
Parameter containing:
tensor([-0.3168, -0.0659], requires_grad=True)


### Optimizer
Instead of manually manipulating the weights & biases using gradients, we can use the optimizer `optim.SGD`.

In [9]:
# Define optimizer
opt = torch.optim.SGD(final_model.parameters(), lr=1e-5)

### Loss Function
Instead of defining a loss function manually, we can use the built-in loss function `mse_loss`.

In [10]:
# Import nn.functional
import torch.nn.functional as F

In [11]:
# Define loss function
loss_fn = F.mse_loss

In [12]:
loss = loss_fn(final_model(inputs) , targets)
print(loss)

tensor(5398.3037, grad_fn=<MseLossBackward>)


### Train the model

We are ready to train the model now. We can define a utility function `fit` which trains the model for a given number of epochs.

In [13]:
# Define a utility function to train the model
def fit(num_epochs, final_model, loss_fn, opt):
    for epoch in range(num_epochs):
        for xb,yb in DL:
            # Generate predictions
            pred = final_model(xb)
            loss = loss_fn(pred,yb) #gradient descent
            loss.backward()
            opt.step()
            opt.zero_grad()
    print('Training loss: ', loss_fn(final_model(inputs), targets))


In [14]:

# Train the model for 100 epochs
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(40.5806, grad_fn=<MseLossBackward>)


In [15]:

# Generate predictions
preds = final_model(inputs)
preds

tensor([[ 58.4086,  71.4646],
        [ 80.0169,  96.1801],
        [121.3061, 140.8903],
        [ 28.6024,  43.5989],
        [ 93.6859, 107.5023],
        [ 58.4086,  71.4646],
        [ 80.0169,  96.1801],
        [121.3061, 140.8903],
        [ 28.6024,  43.5989],
        [ 93.6859, 107.5023],
        [ 58.4086,  71.4646],
        [ 80.0169,  96.1801],
        [121.3061, 140.8903],
        [ 28.6024,  43.5989],
        [ 93.6859, 107.5023]], grad_fn=<AddmmBackward>)

In [16]:
# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Now we can define the model, optimizer and loss function exactly as before.

In [17]:
fit(100 , final_model , loss_fn, opt)

Training loss:  tensor(19.1953, grad_fn=<MseLossBackward>)


## Exercise 1:
 Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn (if you want)
 
 
## Exercise 2:
 Try Linear regression on same prediction data using Tensorflow

 

In [18]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70], [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119], 
                    [56, 70], [81, 101], [119, 133], [22, 37], [103, 119]], dtype='float32')

x_shape = inputs.shape

In [19]:

# weights and biases
weights = np.random.rand(2,3)
biases = np.random.rand(15,2)
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.13898026 0.3546745  0.21552273]
 [0.80337204 0.24915495 0.48862539]]
Biases:
[[0.40000139 0.83582459]
 [0.85273612 0.17374302]
 [0.27704909 0.76217291]
 [0.72148474 0.37242697]
 [0.36129579 0.53106804]
 [0.75761238 0.9043629 ]
 [0.23375705 0.22882136]
 [0.68518377 0.13072756]
 [0.29181061 0.69521557]
 [0.64045838 0.1351638 ]
 [0.30918346 0.73050427]
 [0.0742804  0.14636042]
 [0.45892598 0.09774227]
 [0.082071   0.73395554]
 [0.16093845 0.39924308]]


In [20]:
def model(x):
    return x @ np.transpose(weights) + biases

In [21]:
preds = model(inputs)

In [22]:
# Compare with targets
print("Predictions : ", preds, sep="\n")
print("Targets : ",targets, sep="\n")

Predictions : 
[[ 43.57622921  97.18625682]
 [ 58.5047504  126.47825904]
 [ 72.39503305 132.38257597]
 [ 38.12281571 111.10917743]
 [ 59.08627671 114.08639099]
 [ 43.9338402   97.25479514]
 [ 57.88577133 126.53333737]
 [ 72.80316773 131.75113062]
 [ 37.69314158 111.43196603]
 [ 59.3654393  113.69048675]
 [ 43.48541128  97.08093651]
 [ 57.72629468 126.45087644]
 [ 72.57690994 131.71814533]
 [ 37.48340197 111.470706  ]
 [ 58.88591937 113.95456603]]
Targets : 
[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [23]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return np.sum(diff * diff) / len(diff)

In [24]:
# Compute loss
loss = mse(preds, targets)
print(loss)

2389.858668979109


In [25]:
# compute gradients
biases_grad = (preds-targets)*2/x_shape[0]
weights_grad = (np.matmul(np.transpose((preds-targets)),inputs))*2/x_shape[0]

print("weights_grad:",weights_grad, sep="\n")
print("biases_grad:",biases_grad, sep="\n")

weights_grad:
[[-3378.99113313 -5040.38302246 -2872.14011855]
 [ 4577.19727587  2652.33961648  2053.21208954]]
biases_grad:
[[-1.65650277  3.62483424]
 [-2.99936661  3.3971012 ]
 [-6.21399559 -0.0823232 ]
 [ 2.14970876  9.88122366]
 [-5.8551631  -0.65514787]
 [-1.60882131  3.63397268]
 [-3.08189716  3.40444498]
 [-6.15957764 -0.16651592]
 [ 2.09241888  9.92426214]
 [-5.81794143 -0.7079351 ]
 [-1.66861183  3.61079153]
 [-3.10316071  3.39345019]
 [-6.18974534 -0.17091396]
 [ 2.0644536   9.92942747]
 [-5.88187742 -0.67272453]]


Adjust weights

In [26]:
# Adjust weights
weights -= weights_grad * 1e-5
biases -= biases_grad * 1e-5

In [27]:
print("Weights:",weights,sep='\n')
print("Biases:",biases,sep="\n")

Weights:
[[0.17277017 0.40507833 0.24424413]
 [0.75760007 0.22263155 0.46809327]]
Biases:
[[0.40001796 0.83578834]
 [0.85276611 0.17370905]
 [0.27711123 0.76217374]
 [0.72146324 0.37232815]
 [0.36135434 0.5310746 ]
 [0.75762847 0.90432657]
 [0.23378787 0.22878731]
 [0.68524536 0.13072923]
 [0.29178968 0.69511633]
 [0.64051656 0.13517088]
 [0.30920014 0.73046817]
 [0.07431143 0.14632649]
 [0.45898787 0.09774398]
 [0.08205036 0.73385624]
 [0.16099727 0.39924981]]


In [28]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

1749.6766327727626


In [29]:
# repeating same for 200 times
for i in range(200):
    preds = model(inputs)
    loss = mse(preds, targets)
    
    biases_grad = ((((inputs@np.transpose(weights))+biases)-targets))*2/x_shape[0]
    weights_grad = (np.matmul(np.transpose((((inputs@np.transpose(weights))+biases)-targets)),inputs))*2/x_shape[0]

    weights -= weights_grad * 1e-5
    biases -= biases_grad * 1e-5

In [30]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

23.4489781148341


In [31]:
# Print predictions
print(preds)

[[ 57.89066667  71.73759129]
 [ 81.24229173  98.93316408]
 [120.51889145 135.02389973]
 [ 25.12720306  42.25977512]
 [ 97.33043781 113.6525862 ]
 [ 58.24818184  71.80611124]
 [ 80.62347853  98.98822766]
 [120.92691676 134.39262359]
 [ 24.69764407  42.58247722]
 [ 97.60952559 113.25678805]
 [ 57.79987307  71.6322992 ]
 [ 80.46404461  98.90578882]
 [120.7007196  134.35964714]
 [ 24.48796067  42.62120681]
 [ 97.13013416 113.52079656]]


In [32]:
# Print targets
print(targets)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]
 [ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]
